language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
- git config --global user.name "VictoriaHong"
- git config --global user.email "xin.victoria.hong@gmail.com"
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-sitemap --save
script:
- hexo clean
- hexo generate
- hexo deploy
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
