language: node_js

node_js:
- 0.12

branches:
  only:
  - master

before_install:
- npm install -g hexo-cli

before_script:
- git config --global user.name 'VictoriaHong'
- git config --global user.email 'xin.victoria.hong@gmail.com'
- git clone https://github.com/VictoriaHong/website_src.git blog/

script:
- hexo cleanß
- hexo generate

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'CI -> Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
